name: KMP library compilation check

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Core module
      run: ./gradlew -PlibraryPublish :maps:publishToMavenLocal
    - name: Cocoapods install
      run: (cd sample/ios-app && pod install)
    - name: Build GoogleMaps module
      run: ./gradlew -PprovidersPublish :maps-google:publishToMavenLocal
    - name: Build MapBox module
      run: ./gradlew -PprovidersPublish :maps-mapbox:publishToMavenLocal
